package prop.presentation;

import prop.PropException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.regex.Pattern;

/**
 * Created by quim_motger on 24/05/15.
 */
public class ShowSongPanel extends JPanel {

    private SongPController songPController;
    private SongTabView songTabView;
    private String title;
    private String artist;

    /**
     * Creates a new ShowSongPanel
     * @param scp   the SongPController
     * @param stv   the SongTabView
     * @param t     the title of the song
     * @param a     the artist of the song
     */
    public ShowSongPanel(SongPController scp, SongTabView stv, String t, String a) {
        songPController = scp;
        songTabView = stv;
        title = t;
        artist = a;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        errorText = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        emptyPanel = new javax.swing.JPanel();


        SpinnerNumberModel durationModel = new SpinnerNumberModel(1,1,999999,1);
        jSpinner2 = new javax.swing.JSpinner(durationModel);


        Calendar cal = Calendar.getInstance();
        SpinnerNumberModel yearModel = new SpinnerNumberModel(cal.get(Calendar.YEAR),1,cal.get(Calendar.YEAR),1);
        jSpinner1 = new JSpinner(yearModel);

        jLabel1.setText("Song details");

        jLabel8.setText("Duration");

        jLabel6.setText("Genre");

        jLabel7.setText("Subgenre");

        jLabel2.setText("Title");

        jLabel4.setText("Album");

        jLabel3.setText("Artist");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel5.setText("Year");

        errorText.setForeground(Color.RED);
        errorText.setVisible(false);
        errorText.setText("Error: ");

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButton(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButton(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(songPController.listGenres()));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(songPController.listGenres()));

        try {
            String[] attr = songPController.getSong(title,artist).split(Pattern.quote("|"));
            jTextField1.setText(attr[0]);
            jTextField2.setText(attr[1]);
            jTextField3.setText(attr[2]);
            int y = Integer.parseInt(attr[3]);
            jSpinner1.setValue(y);
            int d = Integer.parseInt(attr[6]);
            jSpinner2.setValue(d);
            jComboBox1.setSelectedIndex(Integer.parseInt(attr[4]));
            jComboBox2.setSelectedIndex(Integer.parseInt(attr[5]));
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            jTextField3.setEditable(false);
            jComboBox1.setEnabled(false);
            jComboBox2.setEnabled(false);
            jSpinner1.setEnabled(false);
            jSpinner2.setEnabled(false);
            editButton.setEnabled(true);
            removeButton.setEnabled(true);
            saveButton.setEnabled(false);
            cancelButton.setEnabled(false);
        } catch (PropException e) {
            e.printStackTrace();
            errorText.setText(e.getMessage());
            errorText.setVisible(true);
            ActionListener listener = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    errorText.setVisible(false);
                }
            };
            Timer timer = new Timer(4000, listener);
            timer.start();
        }



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(errorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel2)
                                                .addGap(239, 239, 239))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator1)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(30, 30, 30)
                                                                                .addComponent(jLabel3))
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jTextField2)
                                                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(87, 87, 87)
                                                                .addComponent(jTextField1))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabel8)
                                                                                        .addComponent(jLabel7)
                                                                                        .addComponent(jLabel6))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(191, Short.MAX_VALUE)
                                .addComponent(editButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(editButton)
                                        .addComponent(removeButton)
                                        .addComponent(saveButton)
                                        .addComponent(cancelButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(errorText))
        );
    }// </editor-fold>

    private void editButton(java.awt.event.ActionEvent evt) {
        jTextField1.setEditable(true);
        jTextField2.setEditable(true);
        jTextField3.setEditable(true);
        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(true);
        jSpinner1.setEnabled(true);
        jSpinner2.setEnabled(true);
        editButton.setEnabled(false);
        removeButton.setEnabled(false);
        saveButton.setEnabled(true);
        cancelButton.setEnabled(true);
    }


    private void saveButton(java.awt.event.ActionEvent evt) {
        try {
            int y = (Integer) jSpinner1.getValue();
            int d = (Integer) jSpinner2.getValue();
            if (title != jTextField1.getText().trim()) {
                songPController.edit(title,artist,"title",jTextField1.getText().trim());
                title = jTextField1.getText().trim();
            }
            if (artist != jTextField2.getText().trim()) {
                songPController.edit(title,artist,"artist",jTextField2.getText().trim());
                artist = jTextField2.getText().trim();
            }
            songPController.edit(title,artist,"album",jTextField3.getText());
            songPController.edit(title,artist,"year",String.valueOf(y));
            songPController.edit(title, artist, "genre", String.valueOf(jComboBox1.getSelectedIndex()));
            songPController.edit(title,artist,"subgenre",String.valueOf(jComboBox2.getSelectedIndex()));
            songPController.edit(title,artist,"duration",String.valueOf(d));
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            jTextField3.setEditable(false);
            jComboBox1.setEnabled(false);
            jComboBox2.setEnabled(false);
            jSpinner1.setEnabled(false);
            jSpinner2.setEnabled(false);
            editButton.setEnabled(true);
            removeButton.setEnabled(true);
            saveButton.setEnabled(false);
            cancelButton.setEnabled(false);
            songTabView.updateSongSetModel();
        } catch (PropException e) {
            e.printStackTrace();
            errorText.setText(e.getMessage());
            errorText.setVisible(true);
            ActionListener listener = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    errorText.setVisible(false);
                }
            };
            Timer timer = new Timer(4000, listener);
            timer.start();
        }
    }

    private void cancelButton(java.awt.event.ActionEvent evt) {
        try {
            String[] attr = songPController.getSong(title,artist).split(Pattern.quote("|"));
            jTextField1.setText(attr[0]);
            jTextField2.setText(attr[1]);
            jTextField3.setText(attr[2]);
            int y = Integer.parseInt(attr[3]);
            jSpinner1.setValue(y);
            int d = Integer.parseInt(attr[6]);
            jSpinner2.setValue(d);
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            jTextField3.setEditable(false);
            jComboBox1.setEnabled(false);
            jComboBox2.setEnabled(false);
            jSpinner1.setEnabled(false);
            jSpinner2.setEnabled(false);
            editButton.setEnabled(true);
            removeButton.setEnabled(true);
            saveButton.setEnabled(false);
            cancelButton.setEnabled(false);
        } catch (PropException e) {
            e.printStackTrace();
            errorText.setText(e.getMessage());
            errorText.setVisible(true);
            ActionListener listener = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    errorText.setVisible(false);
                }
            };
            Timer timer = new Timer(4000, listener);
            timer.start();
        }
    }

    private void removeButton(java.awt.event.ActionEvent evt) {
        try {
            songPController.removeSong(title, artist);
            songTabView.updateSongSetModel();
            songTabView.setRightPanel(emptyPanel);
        } catch (PropException e) {
            e.printStackTrace();
        }

    }


    // Variables declaration - do not modify
    private javax.swing.JButton editButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel errorText;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JPanel emptyPanel;

}

